name: iOS

on:
  push:
    branches: [ main, "version-*" ]
  pull_request:
    branches: [ "main" ]
    types: [ labeled, synchronize, opened, reopened ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ios-build-main-{0}', github.sha) || format('ios-build-pr-{0}', github.ref)  }}
  cancel-in-progress: true

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'iOS'))  
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Rust & Cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.76
        profile: minimal
        override: true

    - name: Install targets
      run: make targets-ios

    - name: Set XCode 15.2
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app

    - name: Build framework & bindings
      run: make ios

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: get_branch

    - name: Unit test coverage
      working-directory: platforms/ios/example
      run: exec ./ios-test-coverage.sh

    - name: Run slather for unit tests
      run: bundle exec slather
      env:
        GIT_BRANCH: ${{ steps.get_branch.outputs.branch }}
        CI_PULL_REQUEST: ${{ github.event.number }}

    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: platforms/ios/lib/coverage
        fail_ci_if_error: true
        flags: unittests-ios, unittests
        # https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: UI test coverage
      working-directory: platforms/ios/example
      run: exec ./ios-ui-test-coverage.sh

    - name: Run slather for ui tests
      run: bundle exec slather
      env:
        GIT_BRANCH: ${{ steps.get_branch.outputs.branch }}
        CI_PULL_REQUEST: ${{ github.event.number }}

    - name: Upload ui test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: platforms/ios/lib/coverage
        fail_ci_if_error: true
        flags: uitests-ios, uitests
        # https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
        token: ${{ secrets.CODECOV_TOKEN }}
