name: iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ labeled, synchronize, opened, reopened ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'iOS'))  
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install targets
      run: |
        rustup target add aarch64-apple-ios
        rustup target add aarch64-apple-ios-sim
        rustup target add x86_64-apple-ios

    - name: Install Uniffi
      uses: actions-rs/cargo@v1
      with:
        command: install
        # keep in sync with uniffi dependency in Cargo.toml's
        args: uniffi_bindgen --version 0.21.0

    - name: Set XCode 14.1
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app

    - name: Build framework & bindings
      run: make ios

    - name: Tests
      working-directory: platforms/ios/example
      run: exec ./ios-tests.sh
