name: Publish-iOS

on: [push, workflow_dispatch]

env:
  GH_TOKEN: ${{ secrets.SWIFTPM_GH_TOKEN }}

jobs:
  ios:
    name: Publish to SwiftPM Repo
    runs-on: macos-12
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65
          profile: minimal
          override: true
          
      - name: Install targets
        run: |
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          rustup target add x86_64-apple-ios
          
      - name: Set XCode 14.2
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app

      - name: Set GH Username
        run: git config --global user.name "Velin92"
          
      - name: Release iOS
        run: ./release_ios.sh
