name: Wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Version
      run: rustup default 1.65
    - name: Install `wasm-pack`
      run: cargo install wasm-pack
    - name: Test the `wysiwyg` crate
      working-directory: crates/wysiwyg
      run: wasm-pack test --release --firefox --headless -- --no-default-features --features js
